version: '{build}'
os: Windows Server 2012 R2
clone_folder: c:\gopath\src\github.com\derekparker\delve
environment:
  GOPATH: c:\gopath
install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get github.com/tools/godep
  - "c:\gopath\bin\godep restore"
  - ps: |
    # Install MinGW.
    if (-Not (Test-Path "C:\mingw64")) {
            $file = "x86_64-4.9.2-release-win32-seh-rt_v4-rev3.7z"
            $url  = "https://bintray.com/artifact/download/drewwells/generic/"
            $url += $file
            Invoke-WebRequest -UserAgent wget -Uri $url -OutFile $file
            &7z x -oC:\ $file > $null
    }
  	$env:path = "C:\mingw64\bin;" + $env:path
cache: C:\mingw64
build_script:
- mingw32-make install
test_script:
- mingw32-make test